<?php
 use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
/**
 * Implements hook_block_view_alter().
 */
function drupify_block_build_alter(array &$build, BlockPluginInterface $block) {
    // Remove the contextual links on all blocks that provide them.
    if($block->getPluginId() === 'system_branding_block'){
        $build['#cache']['contexts'][] = 'url.path';
    }
}

/**
 * Implements hook_entity_presave().
 */
function drupify_misc_entity_presave(EntityInterface $entity) {
    // dd($entity);
    if($entity->getEntityTypeId()==='node' && $entity->bundle()==='page'){
        // $originalTitle = $entity->getTitle();
        // $entity->setTitle($originalTitle.' - Walcome '.date('l'));

    $marks_obtained = $entity->field_marks_obtained->getValue()[0]['value'];
    $total_marks = $entity->field_total_marks->getValue()[0]['value'];
    $percentage = $marks_obtained / $total_marks * 100;
    $entity->field_percentage->setValue($percentage);
    }
  
}